In [2]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt
import pandas as pd

## Datatypes & Atrributes

In [17]:
a1 = np.array([1,2,3])
print(type(a1))

<class 'numpy.ndarray'>


In [40]:
a2 = np.array([[1,2,3],
              [4,5,6.7]])

a3 = np.array([
              [[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]
              ])

In [41]:
sym.sympify(a3)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [42]:
print(np.shape(a1))
print(np.shape(a2))
print(np.shape(a4))

(3,)
(2, 3)
(2, 3, 3)


In [50]:
print(a1.ndim, a2.ndim, a3.ndim)
print(a1.dtype, a2.dtype, a3.dtype)
print(a1.size, a2.size, a3.size)

1 2 3
int64 float64 int64
3 6 18


In [57]:
df = pd.DataFrame(a2, columns=["c1", "c2", "c3"])
df

c1   c2   c3
0  1.0  2.0  3.0
1  4.0  5.0  6.7

## Creating arrays

In [80]:
ar = np.random.randint(0,40, (4,3,3))
ones = np.ones((2,3), dtype=int)
zeros = np.zeros((3,3), dtype=int)
range_array = np.arange(0,22, 2)
range_array_2 = np.random.rand(5,3,2)

In [83]:
 range_array_2

array([[[0.85027615, 0.30183514],
        [0.86684422, 0.53893418],
        [0.45897228, 0.60400212]],

       [[0.19358693, 0.45847477],
        [0.34705415, 0.75539089],
        [0.67103171, 0.27945604]],

       [[0.71366178, 0.20528595],
        [0.92572688, 0.71476074],
        [0.92174008, 0.94132703]],

       [[0.37959742, 0.17018201],
        [0.05297105, 0.74463137],
        [0.60696913, 0.44639394]],

       [[0.78369027, 0.71517792],
        [0.30474937, 0.93031699],
        [0.18297348, 0.98949852]]])

## Random Seeds

Main use of wanting others to generate the same random numbers that we used in our analysis

In [87]:
#Pseudo-random numbers
#kkeps the random generation the same
np.random.seed(seed=0)
ar = np.random.randint(0,40, (4,3))
print(ar)

[[ 0  3  3]
 [39  9 19]
 [21 36 23]
 [ 6 24 24]]


In [89]:
np.random.seed(seed=7)
ar_rand = np.random.random((5,3))
ar_rand

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [94]:
ar = np.random.randint(0,10, (2,10))
print(ar)
np.unique(ar)

[[4 3 1 9 5 9 1 2 3 2]
 [2 5 7 3 0 9 9 3 4 5]]


array([0, 1, 2, 3, 4, 5, 7, 9])

## Viewing vectors and matrices

In [101]:
print(a3)
print("..........")
print(a3[0])
print("..........")
print(a3[0][1])
print("..........")
a3[0][1][-1]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
..........
[[1 2 3]
 [4 5 6]
 [7 8 9]]
..........
[4 5 6]
..........


6

In [110]:
a3[:, :2, :1]

array([[[ 1],
        [ 4]],

       [[10],
        [13]]])

In [114]:
a4 = np.random.randint(0,10, size=(2,3,4,5))
print(a4)
print(a4.shape, a4.ndim)

[[[[0 4 1 7 4]
   [9 0 1 0 6]
   [2 0 2 4 4]
   [1 0 0 2 3]]

  [[7 6 9 3 5]
   [6 8 6 7 3]
   [8 5 6 4 2]
   [7 9 6 8 6]]

  [[1 0 7 6 8]
   [5 4 3 0 7]
   [4 0 8 5 0]
   [7 5 1 5 9]]]


 [[[4 1 9 6 5]
   [6 8 5 9 4]
   [6 0 6 2 3]
   [1 6 7 0 0]]

  [[4 7 0 2 9]
   [6 1 2 2 8]
   [9 7 2 4 7]
   [7 9 1 0 1]]

  [[8 7 4 6 1]
   [4 8 7 3 3]
   [6 4 9 5 7]
   [9 9 7 6 9]]]]
(2, 3, 4, 5) 4


In [120]:
a4[-1:, -1:, 0, :-1]

array([[[8, 7, 4, 6]]])

In [146]:
### Arithmetic 
a2.reshape(3,2)

array([[1. , 2. ],
       [3. , 4. ],
       [5. , 6.7]])

In [145]:
a3.reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [147]:
# How to reshape numpy arays
a2.reshape(3,2) * a3.reshape(3,3,2)

array([[[  1. ,   4. ],
        [  9. ,  16. ],
        [ 25. ,  40.2]],

       [[  7. ,  16. ],
        [ 27. ,  40. ],
        [ 55. ,  80.4]],

       [[ 13. ,  28. ],
        [ 45. ,  64. ],
        [ 85. , 120.6]]])

In [152]:
print(a1)
np.exp(a1)

[1 2 3]


array([ 2.71828183,  7.3890561 , 20.08553692])

### Reshaping and Transposing

In [157]:
a2_reshape = a2.reshape(2,3,1)
a3_reshape = a3.reshape(2,3,3)

print(a2_reshape.shape)
print(a3_reshape.shape)

a2_reshape * a3_reshape

(2, 3, 1)
(2, 3, 3)


array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 21. ,  24. ,  27. ]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [107.2, 113.9, 120.6]]])

In [158]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.7]])

In [161]:
print(a2.T.shape)
a2.T

(3, 2)


array([[1. , 4. ],
       [2. , 5. ],
       [3. , 6.7]])

In [162]:
print(a3.T.shape)
a3.T

(3, 3, 2)


array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

### Dot Product

In [189]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
print(mat1)
print(mat2)

[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]
 [8 8 1]]
[[6 7 7]
 [8 1 5]
 [9 8 9]
 [4 3 0]
 [3 5 0]]


In [190]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

#### Element Wise Product aka Hadamard Product

In [191]:
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

#### Dot Product

In [200]:
mat1T = mat1.T
print("The shape of the transpose and the regular m2 ->", mat1T.shape, mat2.shape)
print(mat1T)
mat_dot = np.dot(mat1T, mat2)
mat_dot2 = mat1T@mat2
print(mat_dot)
print(mat_dot2)

The shape of the transpose and the regular m2 -> (3, 5) (5, 3)
[[5 3 3 4 8]
 [0 7 5 7 8]
 [3 9 2 6 1]]
[[121 114  77]
 [153 108  80]
 [135  69  84]]
[[121 114  77]
 [153 108  80]
 [135  69  84]]


In [194]:
mat1T@mat2

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

### Example of the Butter Sales

In [14]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
price_list = np.array([10,8,12])
price_list = price_list.reshape((1,3))

In [33]:
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", 
                                                 "Wed", "Thurs", "Fri"],
                           columns=["Almond Butter", "Penaut Butter", "Cashew Butter"])

butter_prices = pd.DataFrame(price_list, 
                            columns=["Almond Butter", "Penaut Butter", "Cashew Butter"],
                            index=["Price"])

In [34]:
#shapes arent aligned, letś trnaspose
total_sales = price_list.dot(sales_amounts.T)
print(total_sales)
print(weekly_sales.shape, butter_prices.shape)

[[240 138 458 232 142]]
(5, 3) (1, 3)


In [35]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.T

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [46]:
weekly_sales.loc[:, "Total Sales"]  = daily_sales.T
weekly_sales

Almond Butter  Penaut Butter  Cashew Butter  Total Sales
Mon               12             15              0          240
Tues               3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142

## Comparisons

In [ ]:
type()